### ISSUE TITLE
Performance and crash issue with loading article list

### ISSUE THREAD

**Issue by sssurvey** [sssurvey/reader#89]
- Noticeable lag while scrolling
- Sometimes causing a crash
- Look into: How we load these articles
[ArticleListFragment, ArticleListRepository, ArticleListViewModel]

**Comment by sssurvey** [comment]
I tried to reproduce the crash, but failed, lagging is observed.

**Comment by sssurvey** [comment]
Crash was reproduced, with __OOM__ being the exception:
```
2021-06-24 23:34:06.447 17582-19344/com.haomins.reader2 E/AndroidRuntime: FATAL EXCEPTION: arch_disk_io_0
    Process: com.haomins.reader2, PID: 17582
    java.lang.OutOfMemoryError: Failed to allocate a 24328 byte allocation with 9768 free bytes and 9768B until OOM, target footprint 268435456, growth limit 268435456
        at android.database.CursorWindow.nativeGetString(Native Method)
        at android.database.CursorWindow.getString(CursorWindow.java:480)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
        at com.haomins.data.db.dao.ArticleDao_Impl$4.call(ArticleDao_Impl.java:196)
        at com.haomins.data.db.dao.ArticleDao_Impl$4.call(ArticleDao_Impl.java:168)
        at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
        at io.reactivex.Maybe.subscribe(Maybe.java:4290)
        at io.reactivex.internal.operators.observable.ObservableFlatMapMaybe$FlatMapMaybeObserver.onNext(ObservableFlatMapMaybe.java:113)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by sssurvey** [comment]
Based on the observation, the call in

```kotlin
override fun loadAllArticleItemRefs(): Observable<List<ArticleEntity>> {
        return theOldReaderService
            .loadAllArticles(headerAuthValue = headerAuthValue)
            .doOnError(::onLoadError)
            .flatMapObservable { loadIndividualArticleInformation(it) }                                               // <----- This needs to be looked into
            .onErrorReturn { roomService.articleDao().getAll() }
            .doOnNext { Log.d(TAG, "roomService.articleDao().getAll().toObservable() invoked") } // <----- This call is too much and to often
            .flatMap { roomService.articleDao().getAll().toObservable() }
            .flatMap {
                Observable.just(
                    it.map {
                        articleEntityMapper.dataModelToDomainModel(it)
                    }
                )
            }
    }
```

**Comment by sssurvey** [comment]
After changed the number of articles loaded on each request from 30 to 10, I am not able to observe the issue anymore. However, the UX is pretty bad. Need to address it.
